import { 
  ShieldCheck, 
  ShieldAlert, 
  CheckCircle, 
  AlertTriangle, 
  FileCode, 
  Award, 
  Info,
  Cpu
} from 'lucide-react';

const AnalysisResult = ({ result }) => {
  if (!result) return null;

  const isReal = result.prediction?.toLowerCase() === 'real';
  const confidence = Number(result.confidence) || 0;
  const detectionResult = isReal ? 'REAL' : 'FAKE';
  const visualStatus = isReal ? 'Likely Authentic' : 'Potentially AI-Generated / Manipulated';

  return (
    <div className={`card result-card ${isReal ? 'result-real' : 'result-fake'}`}>
      <div className="result-header">
        <span className="result-chip">
          <Award size={14} /> CNN Prediction Output
        </span>
        <span className="result-timestamp">
          {new Date().toLocaleTimeString()}
        </span>
      </div>

      <div className="result-body">
        {/* Primary Verdict Banner */}
        <div className="verdict-banner">
          <div className="verdict-icon-container">
            {isReal ? (
              <ShieldCheck className="verdict-icon real" size={60} />
            ) : (
              <ShieldAlert className="verdict-icon fake" size={60} />
            )}
          </div>

          <div className="verdict-details">
            <div className="verdict-label-row">
              <span className="verdict-meta-title">Detection Result:</span>
              <h2 className={`verdict-text ${isReal ? 'text-real' : 'text-fake'}`}>
                {detectionResult}
              </h2>
            </div>

            <div className="visual-status-pill-wrap">
              <span className="meta-label">Visual Status:</span>
              <span className={`visual-status-badge ${isReal ? 'status-real' : 'status-fake'}`}>
                {isReal ? <CheckCircle size={15} /> : <AlertTriangle size={15} />}
                <strong>{visualStatus}</strong>
              </span>
            </div>

            <p className="verdict-description">
              {isReal
                ? 'The trained PyTorch CNN evaluated the input features and classified the image as consistent with real media patterns.'
                : 'The trained PyTorch CNN identified visual or neural pattern anomalies indicative of synthetic or manipulated media.'}
            </p>
          </div>
        </div>

        {/* Confidence Meter */}
        <div className="confidence-meter-box">
          <div className="confidence-label-row">
            <span className="meter-title">Confidence:</span>
            <span className={`meter-score ${isReal ? 'score-real' : 'score-fake'}`}>
              {confidence.toFixed(2)}%
            </span>
          </div>

          <div className="confidence-bar-wrapper">
            <div
              className={`confidence-bar-fill ${isReal ? 'fill-real' : 'fill-fake'}`}
              style={{ width: `${Math.min(100, Math.max(0, confidence))}%` }}
            ></div>
          </div>

          <div className="confidence-scale">
            <span>0% (Uncertain)</span>
            <span>50% (Ambiguous)</span>
            <span>100% (High Certainty)</span>
          </div>
        </div>

        {/* File and Execution Metadata Strip */}
        <div className="result-file-strip">
          <div className="strip-item">
            <FileCode size={16} className="strip-icon" />
            <span className="strip-label">Analyzed File:</span>
            <span className="strip-value" title={result.filename}>
              {result.filename}
            </span>
          </div>

          <div className="strip-item">
            <Cpu size={16} className="strip-icon" />
            <span className="strip-label">Model:</span>
            <span className="strip-value">Custom DeepfakeCNN (PyTorch)</span>
          </div>
        </div>

        {/* Responsible AI Disclaimer */}
        <div className="ai-disclaimer-box">
          <Info size={16} className="disclaimer-icon" />
          <p>
            <strong>Note on Media Authenticity:</strong> This result represents probabilistic statistical pattern detection generated by the trained neural network model. It does not constitute definitive proof of authenticity.
          </p>
        </div>
      </div>
    </div>
  );
};

export default AnalysisResult;
